/**
 * Created by lx on 2017/2/26.
 */
export const HANDLE_BUTTON_CLICK = 'HANDLE_BUTTON_CLICK';
export const HANDLE_SELECT_CHANGE = 'HANDLE_SELECT_CHANGE';
export const HANDLE_TEXT_CHANGE = 'HANDLE_TEXT_CHANGE';
